language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.1
  fast_finish: true

before_install:
  - composer self-update
  - composer update --prefer-dist $COMPOSER_FLAGS

script: if [[ "$TRAVIS_PHP_VERSION" == "7.0" && -z "$COMPOSER_FLAGS" ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
