language: php

dist: trusty
sudo: required

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - hhvm

matrix:
  include:
    - php: 7.0
      env: PHPUNIT_FLAGS='--coverage-clover=coverage.clover'
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.1
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - composer install --prefer-dist $COMPOSER_FLAGS

script:
  - bin/phpunit $PHPUNIT_FLAGS

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" && "$COMPOSER_FLAGS" != "" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
